package clases;

public enum Position {
    ARQUERO, LATERAL_DERECHO, CENTRAL_DERECHO, CENTRAL_IZQUIERDO, LATERAL_IZQUIERDO, VOLANTE_CENTRAL, DOBLE_CINCO, ENGANCHE,
    INTERIOR_IZQUIERDO, INTERIOR_DERECHO, EXTREMO_DERECHO, EXTREMO_IZQUIERDO, DELANTERO
}
